"""Create role-collection many-to-many association

Revision ID: 8aabf7e0521d
Revises: 0afc2589d677
Create Date: 2022-11-16 09:07:03.720418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aabf7e0521d'
down_revision = '0afc2589d677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('role_collection',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'collection_id')
    )
    op.add_column('role', sa.Column('collection_specific', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint('role_collection_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'collection_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('role', sa.Column('collection_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('role_collection_id_fkey', 'role', 'collection', ['collection_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('role', 'collection_specific')
    op.drop_table('role_collection')
    # ### end Alembic commands ###
