"""Create provider audit log

Revision ID: 503fc5a0b3f2
Revises: e88db40132d0
Create Date: 2022-12-05 16:37:50.188754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '503fc5a0b3f2'
down_revision = 'e88db40132d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted enum ref ###
    op.create_table('provider_audit',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('command', postgresql.ENUM(name='auditcommand', create_type=False), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('_key', sa.String(), nullable=False),
    sa.Column('_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('provider_audit')
    # ### end Alembic commands ###
