"""Provider and collection UUIDs

Revision ID: da9bb40789b0
Revises: 8aabf7e0521d
Create Date: 2022-11-30 15:14:42.220208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9bb40789b0'
down_revision = '8aabf7e0521d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('collection', sa.Column('key', sa.String(), nullable=False))
    op.create_unique_constraint('collection_key_key', 'collection', ['key'])
    op.drop_constraint('collection_provider_id_fkey', 'collection', type_='foreignkey')
    op.create_foreign_key('collection_provider_id_fkey', 'collection', 'provider', ['provider_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('collection_tag_collection_id_fkey', 'collection_tag', type_='foreignkey')
    op.create_foreign_key('collection_tag_collection_id_fkey', 'collection_tag', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.add_column('provider', sa.Column('key', sa.String(), nullable=False))
    op.create_unique_constraint('provider_key_key', 'provider', ['key'])
    op.drop_constraint('record_collection_id_fkey', 'record', type_='foreignkey')
    op.create_foreign_key('record_collection_id_fkey', 'record', 'collection', ['collection_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('record_collection_id_fkey', 'record', type_='foreignkey')
    op.create_foreign_key('record_collection_id_fkey', 'record', 'collection', ['collection_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint('provider_key_key', 'provider', type_='unique')
    op.drop_column('provider', 'key')
    op.drop_constraint('collection_tag_collection_id_fkey', 'collection_tag', type_='foreignkey')
    op.create_foreign_key('collection_tag_collection_id_fkey', 'collection_tag', 'collection', ['collection_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('collection_provider_id_fkey', 'collection', type_='foreignkey')
    op.create_foreign_key('collection_provider_id_fkey', 'collection', 'provider', ['provider_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('collection_key_key', 'collection', type_='unique')
    op.drop_column('collection', 'key')
    # ### end Alembic commands ###
