"""Add catalog record indexes

Revision ID: 8ada7a72f292
Revises: 31f118e34d74
Create Date: 2023-05-08 18:18:30.278485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ada7a72f292'
down_revision = '31f118e34d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_index('ix_catalog_record_catalog_id_published_searchable', 'catalog_record', ['catalog_id', 'published', 'searchable'], unique=False)
    op.create_index('ix_catalog_record_catalog_id_timestamp', 'catalog_record', ['catalog_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index('ix_catalog_record_catalog_id_timestamp', table_name='catalog_record')
    op.drop_index('ix_catalog_record_catalog_id_published_searchable', table_name='catalog_record')
    # ### end Alembic commands ###
