"""Add case-insensitive unique index for DOIs

Revision ID: 7cb5c8d08d82
Revises: 48bf65c26f62
Create Date: 2023-07-21 13:11:42.789427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb5c8d08d82'
down_revision = '48bf65c26f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_index('ix_published_record_doi', 'published_record', [sa.text('lower(doi)')], unique=True)
    op.create_index('ix_record_doi', 'record', [sa.text('lower(doi)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index('ix_record_doi', table_name='record')
    op.drop_index('ix_published_record_doi', table_name='published_record')
    # ### end Alembic commands ###
