"""Link package to provider

Revision ID: 1eea59d91fea
Revises: 220060b4adb3
Create Date: 2023-11-23 14:48:06.777908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eea59d91fea'
down_revision = '220060b4adb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('package', sa.Column('provider_id', sa.String(), nullable=False))
    op.create_foreign_key('package_provider_id_fkey', 'package', 'provider', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('package_provider_id_fkey', 'package', type_='foreignkey')
    op.drop_column('package', 'provider_id')
    # ### end Alembic commands ###
