"""Add more catalog record indexes

Revision ID: 2a11221f8547
Revises: 8ada7a72f292
Create Date: 2023-05-09 19:04:45.680002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a11221f8547'
down_revision = '8ada7a72f292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_index('ix_catalog_record_full_text', 'catalog_record', ['full_text'], unique=False, postgresql_using='gin')
    op.create_index('ix_catalog_record_spatial', 'catalog_record', ['spatial_north', 'spatial_east', 'spatial_south', 'spatial_west'], unique=False)
    op.create_index(op.f('ix_catalog_record_temporal_end'), 'catalog_record', ['temporal_end'], unique=False)
    op.create_index(op.f('ix_catalog_record_temporal_start'), 'catalog_record', ['temporal_start'], unique=False)
    op.create_index('ix_catalog_record_facet_catalog_id_facet_value', 'catalog_record_facet', ['catalog_id', 'facet', 'value'], unique=False)
    op.create_index(op.f('ix_catalog_record_facet_record_id'), 'catalog_record_facet', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_catalog_record_facet_record_id'), table_name='catalog_record_facet')
    op.drop_index('ix_catalog_record_facet_catalog_id_facet_value', table_name='catalog_record_facet')
    op.drop_index(op.f('ix_catalog_record_temporal_start'), table_name='catalog_record')
    op.drop_index(op.f('ix_catalog_record_temporal_end'), table_name='catalog_record')
    op.drop_index('ix_catalog_record_spatial', table_name='catalog_record')
    op.drop_index('ix_catalog_record_full_text', table_name='catalog_record', postgresql_using='gin')
    # ### end Alembic commands ###
