"""Add global catalog data

Revision ID: df57d06e1ee5
Revises:
Create Date: 2023-10-30 11:41:39.261576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df57d06e1ee5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('catalog', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('catalog', sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('catalog', 'timestamp')
    op.drop_column('catalog', 'data')
    # ### end Alembic commands ###
