"""Create parent-child record relationship

Revision ID: aa0153edf5a9
Revises: 48bf65c26f62
Create Date: 2023-07-19 13:58:52.518432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0153edf5a9'
down_revision = '48bf65c26f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('record', sa.Column('parent_id', sa.String(), nullable=True))
    op.create_foreign_key('record_parent_id_fkey', 'record', 'record', ['parent_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('record_parent_id_fkey', 'record', type_='foreignkey')
    op.drop_column('record', 'parent_id')
    # ### end Alembic commands ###
