"""Add parent_id to record audit log

Revision ID: df471c7d7f99
Revises: 9f52b3064a2f
Create Date: 2023-07-24 11:12:11.446907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df471c7d7f99'
down_revision = '9f52b3064a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('record_audit', sa.Column('_parent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('record_audit', '_parent_id')
    # ### end Alembic commands ###
