"""Create archive and package entities

Revision ID: 220060b4adb3
Revises: df57d06e1ee5
Create Date: 2023-11-20 14:59:44.964701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '220060b4adb3'
down_revision = 'df57d06e1ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('archive',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('archive_resource',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('path', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.Column('md5', sa.String(), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('archive_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['archive_id'], ['archive.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('archive_id', 'key', name='uix_archive_resource_archive_id_key')
                    )
    op.create_table('package',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('record_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('package_resource',
                    sa.Column('package_id', sa.String(), nullable=False),
                    sa.Column('resource_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['resource_id'], ['archive_resource.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('package_id', 'resource_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('package_resource')
    op.drop_table('package')
    op.drop_table('archive_resource')
    op.drop_table('archive')
    # ### end Alembic commands ###
