"""Add provider reference to role

Revision ID: e139ee351ea6
Revises: aafca5cd1ec0
Create Date: 2023-12-22 11:42:54.123722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e139ee351ea6'
down_revision = 'aafca5cd1ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('role', sa.Column('provider_id', sa.String(), nullable=True))
    op.create_foreign_key('role_provider_id_fkey', 'role', 'provider', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('role_provider_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'provider_id')
    # ### end Alembic commands ###
