"""Add catalog URL

Revision ID: be3559ff9387
Revises: 5e5cc2feacd5
Create Date: 2023-01-12 08:44:58.433263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3559ff9387'
down_revision = '5e5cc2feacd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('catalog', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('catalog', 'url')
    # ### end Alembic commands ###
