"""Create one-to-many record-package association table

Revision ID: cf2750a8fc1e
Revises: e139ee351ea6
Create Date: 2023-12-22 15:17:06.209326

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cf2750a8fc1e'
down_revision = 'e139ee351ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('record_package',
                    sa.Column('record_id', sa.String(), nullable=False),
                    sa.Column('package_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('record_id', 'package_id'),
                    sa.UniqueConstraint('package_id')
                    )
    op.drop_constraint('package_record_id_fkey', 'package', type_='foreignkey')
    op.drop_column('package', 'record_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('package', sa.Column('record_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('package_record_id_fkey', 'package', 'record', ['record_id'], ['id'], ondelete='SET NULL')
    op.drop_table('record_package')
    # ### end Alembic commands ###
