"""Create archive, resource and package entities

Revision ID: aafca5cd1ec0
Revises: df57d06e1ee5
Create Date: 2023-12-22 11:30:17.092518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aafca5cd1ec0'
down_revision = 'df57d06e1ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('archive',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('resource',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('type', sa.Enum('file', 'folder', 'webpage', name='resourcetype'), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('size', sa.BigInteger(), nullable=True),
                    sa.Column('md5', sa.String(), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('archive_id', sa.String(), nullable=False),
                    sa.Column('provider_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['archive_id'], ['archive.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('package',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('provider_id', sa.String(), nullable=False),
                    sa.Column('record_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('package_resource',
                    sa.Column('package_id', sa.String(), nullable=False),
                    sa.Column('resource_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('package_id', 'resource_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - plus 'drop type' ###
    op.drop_table('package_resource')
    op.drop_table('package')
    op.drop_table('resource')
    op.drop_table('archive')
    op.execute('drop type resourcetype')
    # ### end Alembic commands ###
