"""Add optional vocab to tag def

Revision ID: 48bf65c26f62
Revises: 5488cb6ae87d
Create Date: 2023-06-26 00:06:57.020877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bf65c26f62'
down_revision = '5488cb6ae87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('tag', sa.Column('vocabulary_id', sa.String(), nullable=True))
    op.create_foreign_key('tag_vocabulary_id_fkey', 'tag', 'vocabulary', ['vocabulary_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('tag_vocabulary_id_fkey', 'tag', type_='foreignkey')
    op.drop_column('tag', 'vocabulary_id')
    # ### end Alembic commands ###
