"""Save published record ids

Revision ID: f1913131f924
Revises: 2f612ad23b6b
Create Date: 2023-01-06 09:41:36.006594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1913131f924'
down_revision = '2f612ad23b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('published_record',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('doi', sa.String(), nullable=True),
                    sa.Column('id_published', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('doi_published', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['doi'], ['record.doi'], onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['id'], ['record.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('doi')
                    )
    op.drop_table('published_doi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('published_doi',
                    sa.Column('doi', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('published', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['doi'], ['record.doi'], name='published_doi_doi_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('doi', name='published_doi_pkey')
                    )
    op.drop_table('published_record')
    # ### end Alembic commands ###
