"""Create parent-child record relationship

Revision ID: 9f52b3064a2f
Revises: 7cb5c8d08d82
Create Date: 2023-07-21 14:08:44.199331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f52b3064a2f'
down_revision = '7cb5c8d08d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('record', sa.Column('parent_id', sa.String(), nullable=True))
    op.create_foreign_key('record_parent_id_fkey', 'record', 'record', ['parent_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('record_parent_id_fkey', 'record', type_='foreignkey')
    op.drop_column('record', 'parent_id')
    # ### end Alembic commands ###
