"""Create catalog_record_facet table

Revision ID: 31f118e34d74
Revises: 22c27429c04b
Create Date: 2023-03-10 15:55:06.180385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f118e34d74'
down_revision = '22c27429c04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_record_facet',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('catalog_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('facet', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id', 'record_id'], ['catalog_record.catalog_id', 'catalog_record.record_id'], name='catalog_record_facet_catalog_record_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_record_facet')
    # ### end Alembic commands ###
