"""Add searchable catalog record indicator

Revision ID: e91656ef5b71
Revises: d442393edc71
Create Date: 2023-01-27 11:22:56.109675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91656ef5b71'
down_revision = 'd442393edc71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('catalog_record', sa.Column('searchable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('catalog_record', 'searchable')
    # ### end Alembic commands ###
