"""Add scope and adapter to archive

Revision ID: 23e051502f55
Revises: d07b0722f477
Create Date: 2024-08-22 16:32:34.683847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '23e051502f55'
down_revision = 'd07b0722f477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.execute("create type archiveadapter as enum ('filesystem', 'nextcloud', 'website')")
    op.add_column('archive', sa.Column('adapter', postgresql.ENUM(name='archiveadapter', create_type=False), nullable=False))
    op.add_column('archive', sa.Column('scope_id', sa.String(), nullable=False))
    op.add_column('archive', sa.Column('scope_type', postgresql.ENUM(name='scopetype', create_type=False), nullable=False))
    op.create_foreign_key('archive_scope_fkey', 'archive', 'scope', ['scope_id', 'scope_type'], ['id', 'type'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('archive_scope_fkey', 'archive', type_='foreignkey')
    op.drop_column('archive', 'scope_type')
    op.drop_column('archive', 'scope_id')
    op.drop_column('archive', 'adapter')
    op.execute('drop type archiveadapter')
    # ### end Alembic commands ###
