"""Archive integration

Revision ID: ca716e289ee6
Revises: df57d06e1ee5
Create Date: 2024-01-09 12:03:42.721298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca716e289ee6'
down_revision = 'df57d06e1ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.create_table('archive',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('package',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('provider_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('resource',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('size', sa.BigInteger(), nullable=True),
                    sa.Column('md5', sa.String(), nullable=True),
                    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('provider_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('archive_resource',
                    sa.Column('archive_id', sa.String(), nullable=False),
                    sa.Column('resource_id', sa.String(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['archive_id'], ['archive.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('archive_id', 'resource_id'),
                    sa.UniqueConstraint('archive_id', 'path')
                    )
    op.create_table('package_resource',
                    sa.Column('package_id', sa.String(), nullable=False),
                    sa.Column('resource_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('package_id', 'resource_id')
                    )
    op.create_table('record_package',
                    sa.Column('record_id', sa.String(), nullable=False),
                    sa.Column('package_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('record_id', 'package_id'),
                    sa.UniqueConstraint('package_id')
                    )
    op.add_column('role', sa.Column('provider_id', sa.String(), nullable=True))
    op.create_foreign_key('role_provider_id_fkey', 'role', 'provider', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('role_provider_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'provider_id')
    op.drop_table('record_package')
    op.drop_table('package_resource')
    op.drop_table('archive_resource')
    op.drop_table('resource')
    op.drop_table('package')
    op.drop_table('archive')
    # ### end Alembic commands ###
