"""Redefine archive access points

Revision ID: 5cb26063cc6c
Revises: cecb45343667
Create Date: 2024-09-30 11:56:41.631854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb26063cc6c'
down_revision = 'cecb45343667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('archive', sa.Column('download_url', sa.String(), nullable=True))
    op.add_column('archive', sa.Column('upload_url', sa.String(), nullable=True))
    op.drop_column('archive', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('archive', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('archive', 'upload_url')
    op.drop_column('archive', 'download_url')
    # ### end Alembic commands ###
