"""Temporarily drop keyword

To avoid problems with changing the type of the keyword
primary key, we drop keyword and keyword_audit in this
revision and create the tables afresh in the next.

Revision ID: 75fd0f193787
Revises: 130ed22382ea
Create Date: 2024-12-06 15:29:39.997660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75fd0f193787'
down_revision = '130ed22382ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('keyword_audit')
    op.drop_table('keyword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('keyword',
                    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.Column('status', postgresql.ENUM(name='keywordstatus', create_type=False), nullable=False),
                    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('child_schema_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('child_schema_type', postgresql.ENUM(name='schematype', create_type=False), nullable=True),
                    sa.CheckConstraint("child_schema_type = 'keyword'::schematype", name='keyword_child_schema_type_check'),
                    sa.CheckConstraint('parent_id IS NOT NULL OR child_schema_id IS NOT NULL', name='keyword_root_child_schema_check'),
                    sa.CheckConstraint('parent_id IS NULL OR starts_with(id::text, parent_id::text)', name='keyword_parent_id_suffix_check'),
                    sa.ForeignKeyConstraint(['child_schema_id', 'child_schema_type'], ['schema.id', 'schema.type'], name='keyword_child_schema_fkey',
                                            ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['parent_id'], ['keyword.id'], name='keyword_parent_id_fkey', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id', name='keyword_pkey')
                    )
    op.create_table('keyword_audit',
                    sa.Column('id', sa.INTEGER(),
                              sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
                              autoincrement=True, nullable=False),
                    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('command', postgresql.ENUM(name='auditcommand', create_type=False), nullable=False),
                    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
                    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.Column('_status', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('_parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('_child_schema_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='keyword_audit_pkey')
                    )
    # ### end Alembic commands ###
