"""Add path to package_resource

Revision ID: d07b0722f477
Revises: fa61305a87a4
Create Date: 2024-08-19 18:40:21.028852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07b0722f477'
down_revision = 'fa61305a87a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_column('package', 'notes')
    op.drop_column('package_audit', '_notes')
    op.add_column('package_resource', sa.Column('path', sa.String(), nullable=False))
    op.add_column('package_resource', sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False))
    op.create_unique_constraint('package_resource_package_id_path_key', 'package_resource', ['package_id', 'path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('package_resource_package_id_path_key', 'package_resource', type_='unique')
    op.drop_column('package_resource', 'timestamp')
    op.drop_column('package_resource', 'path')
    op.add_column('package_audit', sa.Column('_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('package', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
