"""Add upload dir to archive

Revision ID: e64766d96146
Revises: cecb45343667
Create Date: 2024-09-28 15:13:41.537405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64766d96146'
down_revision = 'cecb45343667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('archive', sa.Column('dir', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('archive', 'dir')
    # ### end Alembic commands ###
