"""Drop package title

Revision ID: a11365fc0f5a
Revises: 934b228ed323
Create Date: 2025-03-18 13:10:12.391468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11365fc0f5a'
down_revision = '934b228ed323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('package', 'title')
    op.drop_column('package_audit', '_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('package_audit', sa.Column('_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('package', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
