"""Merge folder and filename into path

Revision ID: c8363345ee8c
Revises: b9774b38ac0b
Create Date: 2025-04-21 16:05:08.099042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8363345ee8c'
down_revision = 'b9774b38ac0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('resource', sa.Column('path', sa.String(), nullable=False))
    op.create_unique_constraint('resource_package_id_path_key', 'resource', ['package_id', 'path'])
    op.drop_index('resource_package_path_uix', 'resource')
    op.drop_column('resource', 'filename')
    op.drop_column('resource', 'folder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('resource', sa.Column('folder', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('resource_package_path_uix', 'resource', [sa.text("(package_id || '/' || folder || '/' || filename)")], unique=True)
    op.drop_constraint('resource_package_id_path_key', 'resource', type_='unique')
    op.drop_column('resource', 'path')
    # ### end Alembic commands ###
