"""Add resource status

Revision ID: 660293c24387
Revises: 9a8a50aea902
Create Date: 2025-04-10 17:53:16.186335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '660293c24387'
down_revision = '9a8a50aea902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.execute("create type resourcestatus as enum ('pending', 'valid', 'missing', 'corrupt', 'delete_pending')")
    op.add_column('archive_resource', sa.Column('status', postgresql.ENUM(name='resourcestatus', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_column('archive_resource', 'status')
    op.execute('drop type resourcestatus')
    # ### end Alembic commands ###
