"""Add metadata fields to package

Revision ID: 9345e099fecc
Revises: 520387a64059
Create Date: 2025-02-06 17:35:36.197299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9345e099fecc'
down_revision = '520387a64059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('package', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('package', sa.Column('validity', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('package', sa.Column('schema_id', sa.String(), nullable=False))
    op.add_column('package', sa.Column('schema_type', postgresql.ENUM(name='schematype', create_type=False), nullable=False))
    op.create_foreign_key('package_schema_fkey', 'package', 'schema', ['schema_id', 'schema_type'], ['id', 'type'], ondelete='RESTRICT')
    op.create_check_constraint('package_schema_type_check', 'package', "schema_type = 'metadata'")
    op.execute("create type packagecommand as enum ('insert', 'update', 'delete', 'submit', 'cancel')")
    op.drop_column('package_audit', 'command')
    op.add_column('package_audit', sa.Column('command', postgresql.ENUM(name='packagecommand', create_type=False), nullable=False))
    op.add_column('package_audit', sa.Column('_schema_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_column('package_audit', '_schema_id')
    op.drop_column('package_audit', 'command')
    op.add_column('package_audit', sa.Column('command', postgresql.ENUM(name='auditcommand', create_type=False), nullable=False))
    op.execute('drop type packagecommand')
    op.drop_constraint('package_schema_type_check', 'package', type_='check')
    op.drop_constraint('package_schema_fkey', 'package', type_='foreignkey')
    op.drop_column('package', 'schema_type')
    op.drop_column('package', 'schema_id')
    op.drop_column('package', 'validity')
    op.drop_column('package', 'metadata_')
    # ### end Alembic commands ###
