"""Rename archive adapter to type

Revision ID: 9a8a50aea902
Revises: 022554c085f7
Create Date: 2025-04-10 17:09:59.524915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a8a50aea902'
down_revision = '022554c085f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.execute("create type archivetype as enum ('filestore', 'website')")
    op.add_column('archive', sa.Column('type', postgresql.ENUM(name='archivetype', create_type=False), nullable=False))
    op.drop_column('archive', 'adapter')
    op.execute('drop type archiveadapter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.execute("create type archiveadapter as enum ('filestore', 'website')")
    op.add_column('archive', sa.Column('adapter', postgresql.ENUM(name='archiveadapter', create_type=False), nullable=False))
    op.drop_column('archive', 'type')
    op.execute('drop type archivetype')
    # ### end Alembic commands ###
