"""Link tag instance to keyword

Revision ID: 520387a64059
Revises: 965353b36e2f
Create Date: 2025-01-06 15:11:24.527113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520387a64059'
down_revision = '965353b36e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('collection_tag', sa.Column('vocabulary_id', sa.String(), nullable=True))
    op.add_column('collection_tag', sa.Column('keyword_id', sa.Integer(), nullable=True))
    op.create_foreign_key('collection_tag_keyword_fkey', 'collection_tag', 'keyword', ['vocabulary_id', 'keyword_id'], ['vocabulary_id', 'id'], ondelete='RESTRICT')
    op.add_column('collection_tag_audit', sa.Column('_keyword_id', sa.Integer(), nullable=True))
    op.add_column('package_tag', sa.Column('vocabulary_id', sa.String(), nullable=True))
    op.add_column('package_tag', sa.Column('keyword_id', sa.Integer(), nullable=True))
    op.create_foreign_key('package_tag_keyword_fkey', 'package_tag', 'keyword', ['vocabulary_id', 'keyword_id'], ['vocabulary_id', 'id'], ondelete='RESTRICT')
    op.add_column('package_tag_audit', sa.Column('_keyword_id', sa.Integer(), nullable=True))
    op.add_column('record_tag', sa.Column('vocabulary_id', sa.String(), nullable=True))
    op.add_column('record_tag', sa.Column('keyword_id', sa.Integer(), nullable=True))
    op.create_foreign_key('record_tag_keyword_fkey', 'record_tag', 'keyword', ['vocabulary_id', 'keyword_id'], ['vocabulary_id', 'id'], ondelete='RESTRICT')
    op.add_column('record_tag_audit', sa.Column('_keyword_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('record_tag_audit', '_keyword_id')
    op.drop_constraint('record_tag_keyword_fkey', 'record_tag', type_='foreignkey')
    op.drop_column('record_tag', 'keyword_id')
    op.drop_column('record_tag', 'vocabulary_id')
    op.drop_column('package_tag_audit', '_keyword_id')
    op.drop_constraint('package_tag_keyword_fkey', 'package_tag', type_='foreignkey')
    op.drop_column('package_tag', 'keyword_id')
    op.drop_column('package_tag', 'vocabulary_id')
    op.drop_column('collection_tag_audit', '_keyword_id')
    op.drop_constraint('collection_tag_keyword_fkey', 'collection_tag', type_='foreignkey')
    op.drop_column('collection_tag', 'keyword_id')
    op.drop_column('collection_tag', 'vocabulary_id')
    # ### end Alembic commands ###
