"""Add optional template to schema

Revision ID: 934b228ed323
Revises: 9345e099fecc
Create Date: 2025-02-24 09:58:51.509934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934b228ed323'
down_revision = '9345e099fecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('schema', sa.Column('template_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('schema', 'template_uri')
    # ### end Alembic commands ###
